//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RawCMS.Library.Core.Extension;
using RawCMS.Library.Service;
using RawCMS.Plugins.ApiGateway.Classes;
using RawCMS.Plugins.ApiGateway.Classes.Models;
using RawCMS.Plugins.ApiGateway.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace RawCMS.Plugins.ApiGateway.Middleware
{
    [MiddlewarePriority(Order = 3)]
    public class LoggingMiddleware : GatewayMiddleware
    {
        private readonly CRUDService _crudService;

        public LoggingMiddleware(RequestDelegate requestDelegate, ILogger logger, ApiGatewayConfig config, IEnumerable<RawHandler> handlers, CRUDService crudService)
            : base(requestDelegate, logger, config, handlers)
        {
            this._crudService = crudService;
        }

        public override string Name => "LoggingMiddleware";

        public override string Description => "Enable Logging capability";

        public async override Task InvokeAsync(HttpContext context)
        {
            await next(context);
            try
            {
                if (pluginConfig.Logging.FileEnable)
                {
                    logger.LogInformation($"Request: {context.Request.Path}");
                    logger.LogInformation($"Method: {context.Request.Method}");
                    logger.LogInformation($"Headers: {JsonConvert.SerializeObject(context.Request.Headers)}");
                    if (context.Request.Body != null && context.Request.Body.CanRead)
                    {
                        using (var reader = new StreamReader(context.Request.Body))
                        {
                            logger.LogInformation($"Content: {reader.ReadToEndAsync()}");
                        }
                    }
                    logger.LogInformation("Response************");
                    logger.LogInformation($"Status Code: {context.Response.StatusCode}");
                    logger.LogInformation($"Headers: {JsonConvert.SerializeObject(context.Response.Headers)}");

                    if (context.Response.Body != null && context.Response.Body.CanRead)
                    {
                        using (var reader = new StreamReader(context.Response.Body))
                        {
                            logger.LogInformation($"Content: {reader.ReadToEndAsync()}");
                        }
                    }
                }

                if(pluginConfig.Logging.DBEnable)
                {
                    LogEntity dbLog = new LogEntity()
                    {
                        RequestOn = DateTime.Now,
                        Path = context.Request.Path,
                        Method = context.Request.Method,
                        RequestHeaders = JsonConvert.SerializeObject(context.Request.Headers),
                        ResponseStatus = context.Response.StatusCode,
                        ResponseHeaders = JsonConvert.SerializeObject(context.Response.Headers),
                        RemoteIpAddress = context.Connection.RemoteIpAddress.ToString()
                    };

                    if (context.Request.Body != null && context.Request.Body.CanRead)
                    {
                        using (var reader = new StreamReader(context.Request.Body))
                        {
                            dbLog.RequestContent = await reader.ReadToEndAsync();
                        }
                    }

                    if (context.Response.Body != null && context.Response.Body.CanRead)
                    {
                        using (var reader = new StreamReader(context.Response.Body))
                        {
                            dbLog.ResponseContent = await reader.ReadToEndAsync();
                        }
                    }

                    this._crudService.Insert("_logs", JObject.FromObject(dbLog));
                }
            }
            catch(Exception exc)
            { 
            }
        }
    }
}